"""Parse Cellebrite Summary Report and Quick View PDFs into report fields."""
import re

try:
    import PyPDF2
except Exception:
    PyPDF2 = None


def extract_pdf_text(pdf_path):
    text = ""
    if PyPDF2 is not None:
        with open(pdf_path, "rb") as handle:
            reader = PyPDF2.PdfReader(handle)
            for page in reader.pages:
                text += page.extract_text() or ""
                text += "\n"
        return text
    from pypdf import PdfReader
    reader = PdfReader(pdf_path)
    return "\n".join((page.extract_text() or "") for page in reader.pages)


def classify_mobile_pdf(text, filename=""):
    name = (filename or "").lower()
    body = text or ""
    if re.search(r"Gray\s*[Kk]ey\s+(Progress Report|Software)", body, re.I):
        return "graykey"
    if "Collection Summary Report" in body:
        return "summary"
    if "Device Details" in body and "Application Version" in body and re.search(r"Cellebrite", body, re.I):
        return "summary"
    if "Device identifiers" in body or "Marketing Model" in body:
        return "quickview"
    if "quick view" in name:
        return "quickview"
    if "summaryreport" in name.replace(" ", "") or name.startswith("summary"):
        return "summary"
    if re.search(r"Generated by Cellebrite", body, re.I):
        if "Application Version" in body:
            return "summary"
        return "quickview"
    return "unknown"


def _label_value(text, label):
    pattern = rf"{re.escape(label)}\s+(.+)"
    match = re.search(pattern, text, re.IGNORECASE)
    if not match:
        return ""
    value = match.group(1).strip()
    value = re.split(r"\s{2,}|\n", value)[0].strip()
    return value


def _colon_value(text, label):
    match = re.search(rf"{re.escape(label)}\s*:\s*(.+)", text, re.IGNORECASE)
    if not match:
        return ""
    return match.group(1).strip().split("\n")[0].strip()


def _bullets_after(text, heading, stop_headings):
    flags = re.IGNORECASE
    start = re.search(rf"{re.escape(heading)}\s*", text, flags)
    if not start:
        return []
    rest = text[start.end():]
    stop = None
    for heading_name in stop_headings:
        found = re.search(rf"\n\s*{re.escape(heading_name)}\b", rest, flags)
        if found and (stop is None or found.start() < stop):
            stop = found.start()
    block = rest if stop is None else rest[:stop]
    values = []
    for raw in re.findall(r"[•\-\*]\s*([^\n•]+)", block):
        item = raw.strip()
        if item:
            values.append(item)
    if not values:
        for line in block.splitlines():
            line = line.strip()
            if re.fullmatch(r"[\d+]+", line.replace(" ", "")) or re.match(r"^\+?\d{10,15}$", line):
                values.append(line)
            elif re.match(r"^\d{15,22}$", line):
                values.append(line)
    return values


def _join_unique(values):
    seen = []
    for value in values:
        clean = value.strip()
        if clean and clean not in seen:
            seen.append(clean)
    return ", ".join(seen)


def parse_summary_report(text):
    data = {
        "extraction_tool": "Cellebrite",
        "cellebrite_source": "summary",
    }
    version = _label_value(text, "Application Version")
    if version:
        data["cellebrite_version"] = version

    vendor = _label_value(text, "Device Vendor")
    if vendor:
        data["device_manufacturer"] = vendor.title()

    model = _label_value(text, "Device Model")
    if model:
        data["device_model"] = model

    os_name = _label_value(text, "OS Name")
    os_version = _label_value(text, "OS Version")
    if os_name and os_version:
        data["Device_OS"] = f"{os_name} {os_version}"
    elif os_version:
        data["Device_OS"] = os_version
    elif os_name:
        data["Device_OS"] = os_name

    imei = _label_value(text, "IMEI")
    if imei:
        data["DEV_IMEI"] = imei

    phone = _label_value(text, "Telephone Number")
    if phone:
        data["Phone_Number"] = phone

    email = _label_value(text, "Email")
    if email:
        data["Device_Account"] = email

    bluetooth = _label_value(text, "Device Bluetooth Name")
    if bluetooth:
        data["Device_Name"] = bluetooth

    passcode = _label_value(text, "Passcode")
    if passcode:
        data["device_passcode"] = passcode

    method = _label_value(text, "Extraction Method") or _label_value(text, "Extraction Type")
    if method:
        data["extraction_type"] = method

    start = _label_value(text, "Extraction Start Time")
    if start:
        data["extraction_date"] = start
        data["formatted_date"] = _format_cellebrite_timestamp(start)

    return data


def parse_quick_view(text):
    data = {
        "extraction_tool": "Cellebrite",
        "cellebrite_source": "quickview",
    }
    vendor = _colon_value(text, "Vendor")
    if vendor:
        data["device_manufacturer"] = vendor.title()

    model = _colon_value(text, "Marketing Model") or _colon_value(text, "Model")
    if model:
        data["device_model"] = model

    os_version = _colon_value(text, "OS")
    if os_version:
        data["Device_OS"] = os_version

    device_name = _colon_value(text, "Device Name") or _colon_value(text, "Bluetooth Name")
    if device_name:
        data["Device_Name"] = device_name

    stop = ["Kernel Version", "SPL", "Carrier", "IMSIs", "ICCIDs", "Encryption Type",
            "Device user", "Phone Number", "Email", "Accounts", "Usage details", "Installed Apps"]

    imeis = _bullets_after(text, "IMEIs", stop)
    if imeis:
        # First-listed rule: dual IMEI / multi-carrier / multi-ICCID keep the top value only
        data["DEV_IMEI"] = imeis[0].strip()

    carriers = _bullets_after(text, "Carrier", ["IMSIs", "ICCIDs", "Encryption Type", "Device user"])
    if carriers:
        data["device_carrier"] = carriers[0].strip()

    iccids = _bullets_after(text, "ICCIDs", ["Encryption Type", "Battery Level", "Device State", "Device user"])
    if iccids:
        data["device_iccid"] = iccids[0].strip()

    phones = _bullets_after(text, "Phone Number", ["Email", "Device Name", "Accounts"])
    if phones:
        data["Phone_Number"] = phones[0]
    else:
        phone = _colon_value(text, "Phone Number")
        if phone:
            data["Phone_Number"] = phone

    accounts = _parse_google_account(text)
    if accounts:
        data["Device_Account"] = accounts

    return data


def _parse_google_account(text):
    match = re.search(r"Google account\s+(\S+@\S+)", text, re.IGNORECASE)
    if match:
        return match.group(1).strip()
    match = re.search(r"Email\s+[•\-\*]?\s*(\S+@\S+)", text, re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return ""


def _format_cellebrite_timestamp(value):
    value = (value or "").strip()
    match = re.match(r"(\d{4})-(\d{2})-(\d{2})\s+(\d{2}):(\d{2})", value)
    if not match:
        return value
    year, month, day, hour, minute = (int(part) for part in match.groups())
    from datetime import datetime
    date_obj = datetime(year, month, day, hour, minute)
    formatted = date_obj.strftime("%A, %B %d, %Y").replace(" 0", " ")
    return f"{formatted} at {hour:02d}:{minute:02d}"


def merge_cellebrite_data(*parts):
    merged = {"extraction_tool": "Cellebrite"}
    for part in parts:
        if not part:
            continue
        for key, value in part.items():
            if key == "cellebrite_source":
                continue
            if value in (None, ""):
                continue
            if key not in merged or not merged[key]:
                merged[key] = value
            elif key in ("device_carrier", "DEV_IMEI", "device_iccid") and value != merged[key]:
                # Keep the value already stored (first-listed / UFD-first)
                pass
    return merged



def process_pdf_selection(app, file_paths):
    """Classify dropped/browsed PDFs, prompt for the matching Cellebrite file, and parse."""
    from tkinter import filedialog, messagebox
    import os

    paths = [path for path in file_paths if path]
    for existing in (
        getattr(app, "extraction_file", None),
        getattr(app, "cellebrite_companion_file", None),
    ):
        if existing and str(existing).lower().endswith(".pdf") and existing not in paths:
            paths.append(existing)
    if not paths:
        return {}

    classified = []
    for path in paths:
        try:
            text = extract_pdf_text(path)
        except Exception as exc:
            messagebox.showerror("PDF Processing Error", f"Error reading {os.path.basename(path)}: {exc}")
            continue
        kind = classify_mobile_pdf(text, os.path.basename(path))
        if kind == "unknown":
            from report_common import confirm_pdf_kind
            kind = confirm_pdf_kind(app, kind, path)
        classified.append((path, kind, text))

    if not classified:
        return {}

    kinds = {item[1] for item in classified}
    if "graykey" in kinds and kinds <= {"graykey", "unknown"}:
        app.extraction_file = classified[0][0]
        app.extraction_type = "GrayKey"
        app.cellebrite_companion_file = None
        app.extraction_drop_label.configure(text=f"Selected: {os.path.basename(app.extraction_file)} (GrayKey)")
        return app.parse_pdf_file()

    summary = next((item for item in classified if item[1] == "summary"), None)
    quick = next((item for item in classified if item[1] == "quickview"), None)

    if summary is None and quick is None:
        from report_common import confirm_pdf_kind
        forced = confirm_pdf_kind(app, classified[0][1], classified[0][0])
        if forced == "graykey":
            app.extraction_file = classified[0][0]
            app.extraction_type = "GrayKey"
            app.cellebrite_companion_file = None
            app.extraction_drop_label.configure(
                text=f"Selected: {os.path.basename(app.extraction_file)} (GrayKey)"
            )
            return app.parse_pdf_file()
        classified[0] = (classified[0][0], forced, classified[0][2])
        summary = next((item for item in classified if item[1] == "summary"), None)
        quick = next((item for item in classified if item[1] == "quickview"), None)
        if summary is None and quick is None:
            return {}

    if summary is None or quick is None:
        have_kind = "Summary Report" if summary else "Quick View"
        need_kind = "Quick View" if summary else "Summary Report"
        extra = (
            "The Quick View report usually has ICCID, carrier, and accounts."
            if summary else
            "The Summary Report usually has Cellebrite version, passcode, and extraction date/type."
        )
        should_ask = not getattr(app, "_cellebrite_companion_asked", False)
        app._cellebrite_companion_asked = True
        if should_ask and messagebox.askyesno(
            "Matching Cellebrite PDF",
            f"This looks like a Cellebrite {have_kind} PDF.\n\n"
            f"{extra}\n\nDo you have the corresponding {need_kind} PDF and want to add it?",
        ):
            from report_common import ask_open_file
            companion = ask_open_file(
                [("PDF files", "*.pdf")],
                folder_kind="extraction",
                title=f"Select the Cellebrite {need_kind} PDF",
            )
            if companion:
                try:
                    companion_text = extract_pdf_text(companion)
                    companion_kind = classify_mobile_pdf(companion_text, os.path.basename(companion))
                    classified.append((companion, companion_kind, companion_text))
                    summary = next((item for item in classified if item[1] == "summary"), summary)
                    quick = next((item for item in classified if item[1] == "quickview"), quick)
                except Exception as exc:
                    messagebox.showerror("PDF Processing Error", f"Error reading companion PDF: {exc}")

    parsed_parts = []
    labels = []
    if summary:
        parsed_parts.append(parse_summary_report(summary[2]))
        labels.append(os.path.basename(summary[0]))
        app.extraction_file = summary[0]
    if quick:
        parsed_parts.append(parse_quick_view(quick[2]))
        labels.append(os.path.basename(quick[0]))
        if summary:
            app.cellebrite_companion_file = quick[0]
        else:
            app.extraction_file = quick[0]
            app.cellebrite_companion_file = None

    app.extraction_type = "Cellebrite"
    tag = "Cellebrite Summary + Quick View" if summary and quick else (
        "Cellebrite Summary Report" if summary else "Cellebrite Quick View"
    )
    app.extraction_drop_label.configure(text=f"Selected: {', '.join(labels)} ({tag})")

    merged = merge_cellebrite_data(*parsed_parts)
    phone = merged.get("Phone_Number")
    if phone and hasattr(app, "format_phone_number"):
        merged["Phone_Number"] = app.format_phone_number(phone)
    manufacturer = merged.get("device_manufacturer", "")
    if hasattr(app, "get_article_for_manufacturer"):
        merged["article"] = app.get_article_for_manufacturer(manufacturer)
    _fill_empty_device_fields(app, merged)
    return merged


def parse_cellebrite_pdfs_only(pdf_paths):
    """Parse Summary/Quick View PDFs without changing the primary extraction file."""
    import os
    parts = []
    companions = []
    for path in pdf_paths or []:
        if not path or not str(path).lower().endswith(".pdf"):
            continue
        try:
            text = extract_pdf_text(path)
        except Exception:
            continue
        kind = classify_mobile_pdf(text, os.path.basename(path))
        if kind == "summary":
            parts.append(parse_summary_report(text))
            companions.append(path)
        elif kind == "quickview":
            parts.append(parse_quick_view(text))
            companions.append(path)
    return merge_cellebrite_data(*parts), companions


def _fill_empty_device_fields(app, data):
    mapping = {
        "device_passcode": "device_passcode",
        "device_iccid": "device_iccid",
        "device_carrier": "device_carrier",
    }
    for data_key, widget_name in mapping.items():
        widget = getattr(app, widget_name, None)
        value = data.get(data_key)
        if not widget or not value:
            continue
        try:
            if not widget.get().strip():
                widget.insert(0, value)
        except Exception:
            pass
