"""Factory paragraph text for each report type."""

DEFAULT_PARAGRAPHS = {'mobile_full': {'one_a': '\n'
                          'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                          '{Examiner_Agency} ({Examiner_Agency_Abbr}), took possession of the '
                          'above-described device after it was seized pursuant to a search warrant served on '
                          '{Device_Owner} on {SW_Date}. This particular device, {article} '
                          '{device_manufacturer} {device_model}, will be referred to as the source device '
                          'throughout the remainder of this report.  A forensic examination of the source '
                          'device was authorized by a search warrant.',
                 'one_b': '\n'
                          'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                          '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a forensic '
                          'examination from {Request_Title} {Request_Officer} with the {Request_Agency} '
                          '({Request_Agency_Abbr}). I was advised this particular device, {article} '
                          '{device_manufacturer} {device_model}, belongs to {Device_Owner} and was submitted '
                          'for examination regarding a {Request_Case} investigation.',
                 'one_c': '\n'
                          'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                          '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a forensic '
                          'examination from {Request_Title} {Request_Officer} with the {Request_Agency} '
                          '({Request_Agency_Abbr}). On {Transfer_Date}, custody of the device was '
                          'transferred to me by {Transfer_Title} {Transfer_Officer} with the '
                          '{Transfer_Agency}. I was advised this particular device, {article} '
                          '{device_manufacturer} {device_model}, belongs to {Device_Owner} and was submitted '
                          'for examination regarding a {Request_Case} investigation.',
                 'two_a': '\n'
                          'Upon receiving the source device, I observed airplane mode was enabled. Airplane '
                          'mode disables all the wireless radios of a cellular device. This mode of '
                          'operation eliminates all incoming and outgoing wireless signals to and from the '
                          'device and ensures that no data can be remotely added, deleted, or altered on the '
                          'device.',
                 'two_b': '\n'
                          'Upon receiving the source device, I observed airplane mode was not enabled. '
                          'Airplane mode disables all the wireless radios of a cellular device. This mode of '
                          'operation eliminates all incoming and outgoing wireless signals to and from the '
                          'device and ensures that no data can be remotely added, deleted, or altered on the '
                          'device.',
                 'auth_c': '\n'
                           'While speaking with {Device_Owner}, consent was granted for a forensic '
                           'examination of the source device.',
                 'auth_sw': '\n'
                            '{Request_Title} {Request_Officer_LastName} provided a search warrant, '
                            'authorizing a forensic examination of the source device.',
                 'auth_i': '\n'
                           '{Request_Title} {Request_Officer_LastName} advised {Device_Owner} was deceased, '
                           'authorizing a forensic examination of the source device based on implied '
                           'consent.',
                 'auth_p': '\n'
                           '{Request_Title} {Request_Officer_LastName} advised a forensic examination of the '
                           "source device was authorized by {Device_Owner}'s parole officer.",
                 'three_a': '\n'
                            'The purpose of this forensic examination was to attempt to recover data and '
                            'information contained on the source device that is related to, or is of '
                            'evidentiary value regarding, the {Request_Case} investigation being conducted '
                            'by the {Request_Agency_Abbr}.',
                 'three_b': '\n'
                            'The purpose of this forensic examination was to attempt to recover data and '
                            'information contained on the source device that is related to, or is of '
                            'evidentiary value regarding, the {Request_Case} investigation being conducted '
                            'by the {Examiner_Agency_Abbr}.',
                 'four': '\n\nFORENSIC EXTRACTION',
                 'five_cellebrite': '\n'
                                    'On {formatted_date}, I began the process of obtaining a forensic '
                                    'extraction from the source device. After taking photographs of the '
                                    'source device, I connected the source device to my forensic machine via '
                                    'the Cellebrite device adapter. Utilizing the {extraction_tool} '
                                    'software, I obtained a {extraction_type} extraction from the source '
                                    'device.',
                 'five_cellebrite_multiple': '\n'
                                             'On {formatted_date}, I began the process of obtaining a '
                                             'forensic extraction from the source device. After taking '
                                             'photographs of the source device, I connected the source '
                                             'device to my forensic machine via the Cellebrite device '
                                             'adapter. Utilizing the {extraction_tool} software, I obtained '
                                             'the following extractions: \n'
                                             '* {extraction_type} \n'
                                             '* <ADD ADDITIONAL EXTRACTION TYPE>',
                 'five_graykey': '\n'
                                 'On {formatted_date}, I began the process of obtaining a forensic '
                                 'extraction from the source device. After taking photographs of the source '
                                 'device, I connected it to the GrayKey forensic device. Utilizing the '
                                 '{extraction_tool} software, I obtained a {extraction_type} extraction from '
                                 'the source device. The screenshot below details the device data as seen in '
                                 'the GrayKey interface:\n'
                                 '\n'
                                 '(INSERT HASH SCREENSHOT)',
                 'six': '\n'
                        'A copy of the extracted data will be stored on the {Examiner_Agency_Abbr} Digital '
                        'Evidence Management System.',
                 'seven': '\n\nFORENSIC PROCESSING:',
                 'eight_axiom': '\n'
                                'After the extraction was completed, I used the Axiom forensic software to '
                                'process the data and information that was contained within the data '
                                'extraction(s). Using the forensic software, I was able to recover various '
                                'items of data and information from within the data extraction(s).',
                 'eight_cellebrite': '\n'
                                     'After the extraction was completed, I used the Cellebrite forensic '
                                     'software to process the data and information that was contained within '
                                     'the data extraction(s). Using the forensic software, I was able to '
                                     'recover various items of data and information from within the data '
                                     'extraction(s).',
                 'eight_both': '\n'
                               'After the extraction was completed, I used both the Axiom and Cellebrite '
                               'forensic software to process the data and information that was contained '
                               'within the data extraction(s). Using both forensic software applications, I '
                               'was able to recover various items of data and information from within the '
                               'data extraction(s). The Axiom software provided comprehensive artifact '
                               'analysis and reporting capabilities, while the Cellebrite software offered '
                               'additional extraction and parsing capabilities for mobile device data.',
                 'griffeye_para': '\n'
                                  'Finally, the media from the extracted data was exported from the forensic '
                                  'software and loaded into the Magnet Griffeye forensic software.  Griffeye '
                                  'is specifically geared towards processing media files (images/videos).  I '
                                  'then reviewed and categorized the media files in the Griffeye software.',
                 'nine': '\n\nFINDINGS OF FORENSIC EXAMINATION',
                 'ten': '\n'
                        'During the forensic examination of the source device, I opened and viewed image '
                        '(graphic) files and video (multimedia) files and I examined the content of document '
                        'files and other file types. This included viewing and examining active files and '
                        'deleted files as well as files that were manually carved from various areas within '
                        'the source device.',
                 'eleventeen': '\n'
                               'Next, I examined the Internet artifacts and web related data and information '
                               'that had been recovered from the source device. After that, I examined data '
                               'and information associated with both native and third-party mobile '
                               'applications that were present on the source device. In addition, I examined '
                               'the file system and various operating system related files and information '
                               'including information related to user attribution. Lastly, I conducted '
                               'various keyword searches using terms that were related to this '
                               'investigation.',
                 'twelveteen': '\n'
                               'All the data and information that was of significance or that was of '
                               'evidentiary value that was recovered during the forensic examination of the '
                               'source device was tagged and included in an AXIOM Digital Report created at '
                               'the completion of the examination. The information detailed below is a '
                               'summary of the data and information that is contained in the AXIOM Digital '
                               'Report as well as a description of the contents of each tag that was '
                               'created.',
                 'thirteen': '\n\nAXIOM DIGITAL REPORT',
                 'fourteen': '\n'
                             'For all items described below please refer to the AXIOM Digital Report '
                             'maintained by me in digital format.',
                 'fifteen': '\n'
                            'In the “Case Information” section of the AXIOM Digital Report, I have included '
                            'the information regarding the AXIOM case that was created for this examination '
                            'such as the date and time that the case was created, the case number and a '
                            'description of the digital evidence that was included in the examination.',
                 'sixteen': '\n'
                            'In the “Artifacts” section of the AXIOM Digital Report, I have included all of '
                            'the items of data and information that I tagged during this examination. The '
                            'following is a listing of each artifact type, the tag(s) that I created within '
                            'each artifact type and a description of the data and information contained in '
                            'each tag:',
                 'seventeen': '\n\nARTIFACTS:\n',
                 'Paragraph_NoEv': '\n'
                                   'During the forensic examination of the source device, no data or '
                                   'information of evidentiary value related to this investigation was '
                                   'recovered.'},
 'mobile_portable': {'one_a': '\n'
                              'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                              '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a forensic '
                              'examination from {Request_Title} {Request_Officer} with the {Request_Agency} '
                              '({Request_Agency_Abbr}). I was advised this particular device belongs to '
                              '{Device_Owner} and was submitted for examination regarding a {Request_Case} '
                              'investigation.',
                     'one_b': '\n'
                              'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                              '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a forensic '
                              'examination from {Request_Title} {Request_Officer} with the {Request_Agency} '
                              '({Request_Agency_Abbr}). On {Transfer_Date}, custody of the device was '
                              'transferred to me by {Transfer_Title} {Transfer_Officer} with the '
                              '{Transfer_Agency}. I was advised this particular device belongs to '
                              '{Device_Owner} and was submitted for examination regarding a {Request_Case} '
                              'investigation.',
                     'two': '\n'
                            'The device described in this report consists of {article} {device_manufacturer} '
                            '{device_model}. This device will be referred to as the source device throughout '
                            'the remainder of this report.',
                     'auth_c': '\n'
                               '{Request_Title} {Request_Officer_LastName} advised {Device_Owner} consented '
                               'to a forensic examination of the source device.',
                     'auth_sw': '\n'
                                '{Request_Title} {Request_Officer_LastName} provided a search warrant, '
                                'authorizing a forensic examination of the source device.',
                     'auth_i': '\n'
                               '{Request_Title} {Request_Officer_LastName} advised {Device_Owner} was '
                               'deceased, authorizing a forensic examination of the source device based on '
                               'implied consent.',
                     'auth_p': '\n'
                               '{Request_Title} {Request_Officer_LastName} advised a forensic examination of '
                               "the source device was authorized by {Device_Owner}'s parole officer.",
                     'three_a': '\n'
                                'Upon receiving the source device, I observed airplane mode was enabled. '
                                'Airplane mode disables all the wireless radios of a cellular device. This '
                                'mode of operation eliminates all incoming and outgoing wireless signals to '
                                'and from the device and ensures that no data can be remotely added, '
                                'deleted, or altered on the device.',
                     'three_b': '\n'
                                'Upon receiving the source device, I observed airplane mode was not enabled. '
                                'Airplane mode disables all the wireless radios of a cellular device. This '
                                'mode of operation eliminates all incoming and outgoing wireless signals to '
                                'and from the device and ensures that no data can be remotely added, '
                                'deleted, or altered on the device.',
                     'four': '\n'
                             'The purpose of this forensic examination was to attempt to recover any and all '
                             'data and information contained on the source device that is related to, or is '
                             'of evidentiary value regarding, the {Request_Case} investigation being '
                             'conducted by the {Request_Agency_Abbr}.',
                     'five': '\nFORENSIC EXTRACTION',
                     'six_cellebrite': '\n'
                                       'On {formatted_date}, I began the process of obtaining a forensic '
                                       'extraction from the source device. After taking photographs of the '
                                       'source device, I connected the source device to my forensic machine '
                                       'via the Cellebrite device adapter. Utilizing the {extraction_tool} '
                                       'software, I obtained a {extraction_type} extraction from the source '
                                       'device.',
                     'six_cellebrite_multiple': '\n'
                                                'On {formatted_date}, I began the process of obtaining a '
                                                'forensic extraction from the source device. After taking '
                                                'photographs of the source device, I connected the source '
                                                'device to my forensic machine via the Cellebrite device '
                                                'adapter. Utilizing the {extraction_tool} software, I '
                                                'obtained the following extractions: \n'
                                                '* {extraction_type} \n'
                                                '* <ADD ADDITIONAL EXTRACTION TYPE>',
                     'six_graykey': '\n'
                                    'On {formatted_date}, I began the process of obtaining a forensic '
                                    'extraction from the source device. After taking photographs of the '
                                    'source device, I connected it to the GrayKey forensic device. Utilizing '
                                    'the {extraction_tool} software, I obtained a {extraction_type} '
                                    'extraction from the source device. The screenshot below details the '
                                    'device data as seen in the GrayKey interface:\n'
                                    '(INSERT HASH SCREENSHOT)',
                     'seven_axiom': '\n'
                                    'The extracted data was loaded into the Axiom forensic software. '
                                    'Utilizing the Axiom forensic software, I was able to recover various '
                                    'items of data and information from within the extraction(s).',
                     'seven_cellebrite': '\n'
                                         'The extracted data was loaded into the Cellebrite forensic '
                                         'software. Utilizing the Cellebrite Physical Analyzer forensic '
                                         'software, I was able to recover various items of data and '
                                         'information from within the extraction(s).',
                     'seven_both': '\n'
                                   'The extracted data was loaded into both the Axiom and Cellebrite '
                                   'forensic software. Utilizing both forensic software applications, I was '
                                   'able to recover various items of data and information from within the '
                                   'extraction(s).',
                     'eight': '\n'
                              'After the data and information contained within the extraction had been '
                              'processed using the {Forensic_Software} forensic software, I created a '
                              'portable case of the processed data and provided the report to '
                              '{Request_Title} {Request_Officer_LastName}.',
                     'nine': '\n'
                             'Unless requested, I will not be conducting any further examination of the '
                             'extracted data.',
                     'ten': '\n'
                            'A copy of the extracted data will be stored on the {Examiner_Agency_Abbr} '
                            'Digital Evidence Management System.'},
 'pc_full': {'one_a_computer': '\n'
                               'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                               '{Examiner_Agency} ({Examiner_Agency_Abbr}), took possession of the '
                               'above-described device after it was seized pursuant to a search warrant '
                               'served on {Device_Owner} on {SW_Date}. This particular device, {article} '
                               '{device_PCMan} {device_PCMod}, contained a {device_capacity} {hd_make} '
                               '{hd_model} hard drive.  This hard drive will be referred to as the '
                               '"{source_device}" throughout the remainder of this report. A forensic '
                               'examination of the "{source_device}" was authorized by a search warrant.',
             'one_b_computer': '\n'
                               'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                               '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a '
                               'forensic examination from {Request_Title} {Request_Officer} with the '
                               '{Request_Agency} ({Request_Agency_Abbr}). I was advised this particular '
                               'device, {article} {device_PCMan} {device_PCMod}, containing a '
                               '{device_capacity} {hd_make} {hd_model} hard drive, belongs to {Device_Owner} '
                               'and was submitted for examination regarding a {Request_Case} investigation.  '
                               'This hard drive will be referred to as the "{source_device}" throughout the '
                               'remainder of this report.',
             'one_c_computer': '\n'
                               'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                               '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a '
                               'forensic examination from {Request_Title} {Request_Officer} with the '
                               '{Request_Agency} ({Request_Agency_Abbr}). On {Transfer_Date}, custody of the '
                               'device was transferred to me by {Transfer_Title} {Transfer_Officer} with the '
                               '{Transfer_Agency}. I was advised this particular device, {article} '
                               '({device_PCMan} {device_PCMod} containing a {device_capacity} {hd_make} '
                               '{hd_model} hard drive, belongs to {Device_Owner} and was submitted for '
                               'examination regarding a {Request_Case} investigation.  This hard drive will '
                               'be referred to as the "{source_device}" throughout the remainder of this '
                               'report.',
             'one_a_loose': '\n'
                            'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                            '{Examiner_Agency} ({Examiner_Agency_Abbr}), took possession of the '
                            'above-described device after it was seized pursuant to a search warrant served '
                            'on {Device_Owner} on {SW_Date}. This particular device, a {device_capacity} '
                            '{device_PCMan} {device_PCMod} hard drive, will be referred to as the '
                            '"{source_device}" throughout the remainder of this report. A forensic '
                            'examination of the "{source_device}" was authorized by a search warrant.',
             'one_b_loose': '\n'
                            'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                            '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a forensic '
                            'examination from {Request_Title} {Request_Officer} with the {Request_Agency} '
                            '({Request_Agency_Abbr}). I was advised this particular device, a '
                            '{device_capacity} {device_PCMan} {device_PCMod} hard drive, belongs to '
                            '{Device_Owner} and was submitted for examination regarding a {Request_Case} '
                            'investigation.  This hard drive will be referred to as the "{source_device}" '
                            'throughout the remainder of this report.',
             'one_c_loose': '\n'
                            'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                            '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a forensic '
                            'examination from {Request_Title} {Request_Officer} with the {Request_Agency} '
                            '({Request_Agency_Abbr}). On {Transfer_Date}, custody of the device was '
                            'transferred to me by {Transfer_Title} {Transfer_Officer} with the '
                            '{Transfer_Agency}. I was advised this particular device, a {device_capacity} '
                            '{device_PCMan} {device_PCMod} hard drive, belongs to {Device_Owner} and was '
                            'submitted for examination regarding a {Request_Case} investigation.  This hard '
                            'drive will be referred to as the "{source_device}" throughout the remainder of '
                            'this report.',
             'one_a_storage': '\n'
                              'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                              '{Examiner_Agency} ({Examiner_Agency_Abbr}), took possession of the '
                              'above-described device after it was seized pursuant to a search warrant '
                              'served on {Device_Owner} on {SW_Date}. This particular device, a '
                              '{device_capacity} {device_PCMan} {device_PCMod} {device_type} will be '
                              'referred to as the "{source_device}" throughout the remainder of this report. '
                              'A forensic examination of the "{source_device}" was authorized by a search '
                              'warrant.',
             'one_b_storage': '\n'
                              'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                              '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a forensic '
                              'examination from {Request_Title} {Request_Officer} with the {Request_Agency} '
                              '({Request_Agency_Abbr}). I was advised this particular device, a '
                              '{device_capacity} {device_PCMan} {device_PCMod} {device_type}, belongs to '
                              '{Device_Owner} and was submitted for examination regarding a {Request_Case} '
                              'investigation.  This device will be referred to as the "{source_device}" '
                              'throughout the remainder of this report.',
             'one_c_storage': '\n'
                              'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                              '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a forensic '
                              'examination from {Request_Title} {Request_Officer} with the {Request_Agency} '
                              '({Request_Agency_Abbr}). On {Transfer_Date}, custody of the device was '
                              'transferred to me by {Transfer_Title} {Transfer_Officer} with the '
                              '{Transfer_Agency}. I was advised this particular device, a {device_capacity} '
                              '{device_PCMan} {device_PCMod} {device_type}, belongs to {Device_Owner} and '
                              'was submitted for examination regarding a {Request_Case} investigation.  This '
                              'device will be referred to as the "{source_device}" throughout the remainder '
                              'of this report.',
             'auth_c': '\n'
                       'While speaking with {Device_Owner}, consent was granted for a forensic examination '
                       'of the {source_device}.',
             'auth_sw': '\n'
                        '{Request_Title} {Request_Officer_LastName} provided a search warrant, authorizing a '
                        'forensic examination of the {source_device}.',
             'auth_i': '\n'
                       '{Request_Title} {Request_Officer_LastName} advised {Device_Owner} was deceased, '
                       'authorizing a forensic examination of the {source_device} based on implied consent.',
             'auth_p': '\n'
                       '{Request_Title} {Request_Officer_LastName} advised a forensic examination of the '
                       "{source_device} was authorized by {Device_Owner}'s parole officer.",
             'three_a': '\n'
                        'The purpose of this forensic examination was to attempt to recover data and '
                        'information contained on the {source_device} that is related to, or is of '
                        'evidentiary value regarding, the {Request_Case} investigation being conducted by '
                        'the {Request_Agency_Abbr}.',
             'three_b': '\n'
                        'The purpose of this forensic examination was to attempt to recover data and '
                        'information contained on the {source_device} that is related to, or is of '
                        'evidentiary value regarding, the {Request_Case} investigation being conducted by '
                        'the {Examiner_Agency_Abbr}.',
             'four': '\n\nFORENSIC EXTRACTION',
             'five_tx1': '\n'
                         'On {formatted_date}, I began the process of obtaining a forensic image from the '
                         '{source_device}. After taking photographs of the source device, I used the TX1 '
                         'forensic imaging hardware, with software version {TX1_OS}, to create a '
                         'forensically sound image. The TX1 hardware (Serial #: {extraction_serial}) was '
                         'used to create a forensically sound image, a bit-by-bit duplicate of the '
                         '{source_device}.',
             'five_ftk': '\n'
                         'On {formatted_date}, I began the process of obtaining a forensic image from the '
                         '{source_device}. After taking photographs of the source device, I used the '
                         'AccessData FTK Imager (version {FTK_OS}) to create a forensically sound image, a '
                         'bit-by-bit duplicate of the {source_device}.',
             'five_xways': '\n'
                           'On {formatted_date}, I began the process of obtaining a forensic image from the '
                           '{source_device}. After taking photographs of the source device, I used the '
                           'X-Ways forensic software (version {xways_OS}) to create a forensically sound '
                           'image, a bit-by-bit duplicate of the {source_device}.',
             'five_dc': '\n'
                        'On {formatted_date}, I began the process of obtaining a forensic image from the '
                        '{source_device}. After taking photographs of the source device, I used Cellebrite '
                        'Digital Collector (version {DC_OS}) to create a forensically sound image, a '
                        'bit-by-bit duplicate of the {source_device}.',
             'six': '\n'
                    'A copy of the extracted data will be stored on the {Examiner_Agency_Abbr} Digital '
                    'Evidence Management System.',
             'seven': '\n\nFORENSIC PROCESSING:',
             'eight': '\n'
                      'After the extraction was completed, I used the {Forensic_Software} forensic software '
                      'to process the data and information that was contained within the data extraction(s). '
                      'Using the forensic software, I was able to recover various items of data and '
                      'information from within the data extraction(s).',
             'griffeye_para': '\n'
                              'Finally, the media from the extracted data was exported from the '
                              '{Forensic_Software} forensic software and loaded into the Magnet Griffeye '
                              'forensic software. Griffeye is specifically geared towards processing media '
                              'files (images/videos). I then reviewed and categorized the media files in the '
                              'Griffeye software.',
             'nine': '\n\nFINDINGS OF FORENSIC EXAMINATION',
             'ten': '\n'
                    'During the forensic examination of the source device, I opened and viewed image '
                    '(graphic) files and video (multimedia) files and I examined the content of document '
                    'files and other file types. This included viewing and examining active files and '
                    'deleted files as well as files that were manually carved from various areas within the '
                    'source device.',
             'eleventeen': '\n'
                           'Next, I examined the file system artifacts and metadata. I examined data and '
                           'information associated with both native and third-party applications that were '
                           'present on the source device. In addition, I examined the file system and '
                           'various operating system related files and information including information '
                           'related to user attribution. Lastly, I conducted various keyword searches using '
                           'terms that were related to this investigation.',
             'twelveteen': '\n'
                           'All the data and information that was of significance or that was of evidentiary '
                           'value that was recovered during the forensic examination of the source device '
                           'was tagged and included in an AXIOM Digital Report created at the completion of '
                           'the examination. The information detailed below is a summary of the data and '
                           'information that is contained in the AXIOM Digital Report as well as a '
                           'description of the contents of each tag that was created.',
             'thirteen': '\n\nAXIOM DIGITAL REPORT',
             'fourteen': '\n'
                         'For all items described below please refer to the AXIOM Digital Report maintained '
                         'by me in digital format.',
             'fifteen': '\n'
                        'In the "Case Information" section of the AXIOM Digital Report, I have included the '
                        'information regarding the AXIOM case that was created for this examination such as '
                        'the date and time that the case was created, the case number and a description of '
                        'the digital evidence that was included in the examination.',
             'sixteen': '\n'
                        'In the "Artifacts" section of the AXIOM Digital Report, I have included all of the '
                        'items of data and information that I tagged during this examination. The following '
                        'is a listing of each artifact type, the tag(s) that I created within each artifact '
                        'type and a description of the data and information contained in each tag:',
             'seventeen': '\n\nARTIFACTS:\n',
             'Paragraph_NoEv': '\n'
                               'During the forensic examination of the (source_device), no data or '
                               'information of evidentiary value related to this investigation was '
                               'recovered.'},
 'pc_portable': {'one_b_computer': '\n'
                                   'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                                   '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a '
                                   'forensic examination from {Request_Title} {Request_Officer} with the '
                                   '{Request_Agency} ({Request_Agency_Abbr}). I was advised this particular '
                                   'device, {article} {device_PCMan} {device_PCMod}, containing a '
                                   '{device_capacity} {hd_make} {hd_model} hard drive, belongs to '
                                   '{Device_Owner} and was submitted for examination regarding a '
                                   '{Request_Case} investigation.  This hard drive will be referred to as '
                                   'the "{source_device}" throughout the remainder of this report.',
                 'one_c_computer': '\n'
                                   'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                                   '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a '
                                   'forensic examination from {Request_Title} {Request_Officer} with the '
                                   '{Request_Agency} ({Request_Agency_Abbr}). On {Transfer_Date}, custody of '
                                   'the device was transferred to me by {Transfer_Title} {Transfer_Officer} '
                                   'with the {Transfer_Agency}. I was advised this particular device, '
                                   '{article} ({device_PCMan} {device_PCMod} containing a {device_capacity} '
                                   '{hd_make} {hd_model} hard drive, belongs to {Device_Owner} and was '
                                   'submitted for examination regarding a {Request_Case} investigation.  '
                                   'This hard drive will be referred to as the "{source_device}" throughout '
                                   'the remainder of this report.',
                 'one_b_loose': '\n'
                                'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                                '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a '
                                'forensic examination from {Request_Title} {Request_Officer} with the '
                                '{Request_Agency} ({Request_Agency_Abbr}). I was advised this particular '
                                'device, a {device_capacity} {device_PCMan} {device_PCMod} hard drive, '
                                'belongs to {Device_Owner} and was submitted for examination regarding a '
                                '{Request_Case} investigation.  This hard drive will be referred to as the '
                                '"{source_device}" throughout the remainder of this report.',
                 'one_c_loose': '\n'
                                'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                                '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a '
                                'forensic examination from {Request_Title} {Request_Officer} with the '
                                '{Request_Agency} ({Request_Agency_Abbr}). On {Transfer_Date}, custody of '
                                'the device was transferred to me by {Transfer_Title} {Transfer_Officer} '
                                'with the {Transfer_Agency}. I was advised this particular device, a '
                                '{device_capacity} {device_PCMan} {device_PCMod} hard drive, belongs to '
                                '{Device_Owner} and was submitted for examination regarding a {Request_Case} '
                                'investigation.  This hard drive will be referred to as the '
                                '"{source_device}" throughout the remainder of this report.',
                 'one_b_storage': '\n'
                                  'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                                  '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a '
                                  'forensic examination from {Request_Title} {Request_Officer} with the '
                                  '{Request_Agency} ({Request_Agency_Abbr}). I was advised this particular '
                                  'device, a {device_capacity} {device_PCMan} {device_PCMod} {device_type}, '
                                  'belongs to {Device_Owner} and was submitted for examination regarding a '
                                  '{Request_Case} investigation.  This device will be referred to as the '
                                  '"{source_device}" throughout the remainder of this report.',
                 'one_c_storage': '\n'
                                  'On {Request_Date}, I, {Examiner_Title} {Examiner_Name}, with the '
                                  '{Examiner_Agency} ({Examiner_Agency_Abbr}), received a request for a '
                                  'forensic examination from {Request_Title} {Request_Officer} with the '
                                  '{Request_Agency} ({Request_Agency_Abbr}). On {Transfer_Date}, custody of '
                                  'the device was transferred to me by {Transfer_Title} {Transfer_Officer} '
                                  'with the {Transfer_Agency}. I was advised this particular device, a '
                                  '{device_capacity} {device_PCMan} {device_PCMod} {device_type}, belongs to '
                                  '{Device_Owner} and was submitted for examination regarding a '
                                  '{Request_Case} investigation.  This device will be referred to as the '
                                  '"{source_device}" throughout the remainder of this report.',
                 'auth_c': '\n'
                           '{Request_Title} {Request_Officer_LastName} advised that {Device_Owner} granted '
                           'consent for a forensic examination of the {source_device}.',
                 'auth_sw': '\n'
                            '{Request_Title} {Request_Officer_LastName} provided a search warrant, '
                            'authorizing a forensic examination of the {source_device}.',
                 'auth_i': '\n'
                           '{Request_Title} {Request_Officer_LastName} advised {Device_Owner} was deceased, '
                           'authorizing a forensic examination of the {source_device} based on implied '
                           'consent.',
                 'auth_p': '\n'
                           '{Request_Title} {Request_Officer_LastName} advised a forensic examination of the '
                           "{source_device} was authorized by {Device_Owner}'s parole officer.",
                 'three_a': '\n'
                            'The purpose of this forensic examination was to attempt to recover data and '
                            'information contained on the {source_device} that is related to, or is of '
                            'evidentiary value regarding, the {Request_Case} investigation being conducted '
                            'by the {Request_Agency_Abbr}.',
                 'four': '\n\nFORENSIC EXTRACTION',
                 'five_tx1': '\n'
                             'On {formatted_date}, I began the process of obtaining a forensic image from '
                             'the {source_device}. After taking photographs of the source device, I used the '
                             'TX1 forensic imaging hardware, with software version {TX1_OS}, to create a '
                             'forensically sound image. The TX1 hardware (Serial #: {extraction_serial}) was '
                             'used to create a forensically sound image, a bit-by-bit duplicate of the '
                             '{source_device}.',
                 'five_ftk': '\n'
                             'On {formatted_date}, I began the process of obtaining a forensic image from '
                             'the {source_device}. After taking photographs of the source device, I used the '
                             '{extraction_tool} (version {FTK_OS}) to create a forensically sound image, a '
                             'bit-by-bit duplicate of the {source_device}.',
                 'five_xways': '\n'
                               'On {formatted_date}, I began the process of obtaining a forensic image from '
                               'the {source_device}. After taking photographs of the source device, I used '
                               'the X-Ways forensic software (version {xways_OS}) to create a forensically '
                               'sound image, a bit-by-bit duplicate of the {source_device}.',
                 'five_dc': '\n'
                            'On {formatted_date}, I began the process of obtaining a forensic image from '
                            'the {source_device}. After taking photographs of the source device, I used '
                            'Cellebrite Digital Collector (version {DC_OS}) to create a forensically sound '
                            'image, a bit-by-bit duplicate of the {source_device}.',
                 'six': '\n'
                        'A copy of the extracted data will be stored on the {Examiner_Agency_Abbr} Digital '
                        'Evidence Management System.',
                 'seven': '\n\nFORENSIC PROCESSING:',
                 'eight': '\n'
                          'After the extraction was completed, I used the {Forensic_Software} forensic '
                          'software to process the data and information that was contained within the data '
                          'extraction(s). Using the forensic software, I was able to recover various items '
                          'of data and information from within the data extraction(s).',
                 'nine': '\n'
                         'After the data and information contained within the extraction had been processed '
                         'using the {Forensic_Software} forensic software, I created a portable case of the '
                         'processed data and provided the report to {Request_Title} '
                         '{Request_Officer_LastName}.',
                 'ten': '\n'
                        'Unless requested, I will not be conducting any further examination of the extracted '
                        'data.'},
 'warrant': {'intro_self': 'On {Warrant_Service_Date}, a search warrant was served on {Service_Provider} for the data '
                           'related to the user account belonging to {Account_Owner} ({Account_Identifier}). On {Data_Return_Date}, I '
                           'received the responsive data from {Service_Provider}. This return consisted of '
                           'approximately {Data_Size}GB of data.',
             'one_ca': '\n'
                       'On {Warrant_Service_Date}, I, {Examiner_Agency_Abbr} {Request_Title} {Request_Officer}, '
                       'submitted a search warrant to {Service_Provider} for the data related to the '
                       '{Service_Provider} user account {Account_Identifier} regarding a {Request_Case} '
                       'investigation.',
             'one_ca_limited': '\n'
                               'On {Warrant_Service_Date}, I, {Examiner_Agency_Abbr} {Request_Title} {Request_Officer}, '
                               'submitted a search warrant to {Service_Provider} for the data related to the '
                               '{Service_Provider} user account {Account_Identifier} between {Time_Frame_Start} and '
                               '{Time_Frame_End} regarding a {Request_Case} investigation.',
             'one_aa': '\n'
                       'On {Request_Date}, I, {Examiner_Title} {Examiner_Name} with the {Examiner_Agency} '
                       '({Examiner_Agency_Abbr}), received a request from {Request_Title} {Request_Officer} with '
                       'the {Request_Agency} ({Request_Agency_Abbr}) to review data obtained pursuant to a search '
                       'warrant served on {Service_Provider} for the {Service_Provider} user account '
                       '{Account_Identifier} regarding a {Request_Case} investigation.',
             'two_aa': '\n'
                       'On {Request_Date}, {Request_Title} {Request_Officer} provided me with the responsive data '
                       'from {Service_Provider}. The following information of interest to this investigation was '
                       'observed relating to the {Service_Provider} account {Account_Identifier}, hereinafter '
                       'referred to as the "source account".',
             'two_ca': '\n'
                       'On {Data_Return_Date}, {Service_Provider} provided responsive data related to the account. '
                       'The following information of interest to this investigation was observed relating to the '
                       '{Service_Provider} account {Account_Identifier}, hereinafter referred to as the "source account".',
             'three_ca': '\n'
                         'In addition to manually reviewing the data, I used the {Forensic_Software} to process the '
                         'information that was contained within the responsive data. Using the forensic software, I '
                         'was able to recover various items of data and information and made the following notable '
                         'observations.',
             'three_b': '\n'
                        'I conducted a manual review of the data and made the following observations:',
             'four_ca': '\n'
                        'All the data and information that was of significance or that was of evidentiary value that '
                        'was observed during the review of the data was tagged and included in {Report_Article} '
                        '{Report_Software} Digital Report created at the completion of the examination. The information '
                        'detailed below is a summary of the data and information that is contained in the '
                        '{Report_Software} Digital Report as well as a description of the contents of each tag that '
                        'was created.',
             'four_ca_multi': '\n'
                              'All the data and information that was of significance or that was of evidentiary value '
                              'that was observed during the review of the data was tagged and included in '
                              '{Report_Software} Digital Reports created at the completion of the examination. The '
                              'information detailed below is a summary of the data and information that is contained '
                              'in the {Report_Software} Digital Reports as well as a description of the contents of '
                              'each tag that was created.'}}
